# Generated by Django 2.2.5 on 2019-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
