# Generated by Django 2.2.5 on 2019-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
