# Generated by Django 2.2.5 on 2019-10-09 10:26

from core.fixtures.users import passwords, usernames
from django.contrib.auth import get_user_model
from django.db import migrations


def add_set_of_users(apps, schema_editor):
    User = get_user_model()
    for index, username in enumerate(usernames):
        user = User.objects.create_user(
            username=username,
            email=f"{username}@best-dojo.com",
            password=passwords[index],
            hint=f"hint for user {username}",
        )
        user.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0005_user_hint")]

    operations = [
        migrations.RunPython(add_set_of_users, reverse_code=migrations.RunPython.noop)
    ]
