# Generated by Django 2.2.5 on 2019-10-09 10:26

from core.fixtures.users import passwords, usernames
from django.contrib.auth.hashers import make_password
from django.db import migrations

colors = ["Rose pâle", "Fuchsia", "Jaune", "Orange", "Vert", "Bleu"]

rooms = [
    "Salle BAM",
    "Salle Métro",
    "Salle Sicara",
    "Salle TBC2",
    "Dojo, cabine téléphonique de droite",
    "Dojo, cabine téléphonique de gauche",
    "Fond de l'open space, cabine téléphonique",
    "Cuisine, derrière Yoda",
]


def add_set_of_users(apps, schema_editor):
    User = apps.get_model("core", "user")
    room_index = 0
    for index, username in enumerate(usernames):
        color_index = index % 6
        color = colors[color_index]

        if color_index == 0:
            room = rooms[room_index]
            room_index += 1

        user = User.objects.create(
            username=username,
            email=f"{username}@best-dojo.com",
            password=make_password(passwords[index]),
            hint=f'Allez chercher votre mot de passe à l\'emplacement "{room}", sur le post-it de couleur {color}',
            hint_color=color,
            hint_location=room,
            explicit_password=passwords[index],
        )
        user.save()


def delete_set_of_users(apps, schema_editor):
    User = apps.get_model("core", "user")
    User.objects.filter(is_staff=False).delete()


class Migration(migrations.Migration):
    dependencies = [("core", "0006_hint_fields")]

    operations = [
        migrations.RunPython(add_set_of_users, reverse_code=delete_set_of_users)
    ]
