# Generated by Django 2.2.5 on 2019-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0007_add_set_of_users")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip_address",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
