# Generated by Django 2.2.5 on 2019-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_add_ip_address_field_to_user_model")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="server_mounted",
            field=models.BooleanField(default=False),
        )
    ]
